version: '3.8'

services:
  app:
    image: golang:1.23
    container_name: go_cacher
    working_dir: /app
    volumes:
      - .:/app
      - /app/go/pkg/mod
    command: go run main.go
    ports:
      - "${HOST_PORT}:${HOST_PORT}"
    environment:
      - GO111MODULE=on
      - CGO_ENABLED=0
      - HOST_PORT=5010 # Map port for container to be available
    networks:
      - go-network

networks:
  go-network:
    driver: bridge
